pipeline {
    agent { label 'worker-node' }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Lenadeesh105/Jenkins.git'

                // Run Maven on a Unix agent
                dir('3-java-jenkins-docker-app') {
                    sh "mvn clean package"
                }
            }
        }

        stage('Test') {
            steps {
                dir('3-java-jenkins-docker-app') {
                    sh "mvn test"
                }
            }
        }

        stage('Compile') {
            steps {
                dir('3-java-jenkins-docker-app') {
                    sh "mvn compile"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('3-java-jenkins-docker-app') {
                    sh "docker build -t java-app ."
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('3-java-jenkins-docker-app') {
                    sh "docker run java-app"
                }
            }
        }

        stage('Docker Push') {
            steps {
                dir('3-java-jenkins-docker-app') {
                        sh "docker login -u lenadeesh -p {password} --stdin"
                        sh "docker tag java-app lenadeesh/java-app:latest"
                        sh "docker push lenadeesh/java-app:latest"
                    }
                }
            }
        }
    }
